name       : rdflib
version    : 5.0.0
release    : 8
source     :
    - https://github.com/RDFLib/rdflib/archive/5.0.0.tar.gz : 05adfb43a7ae8fd35cb7f2f4fe9b4da607d81f926db35d25a941e63693495b22
license    : BSD-3-Clause
component  : programming.python
summary    : RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
description: |
    RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
builddeps  :
    - pkgconfig(python3)
    - pyparsing
    - python-html5lib
    - python-isodate
    - python-nose
    - python-six
    - python-sparqlwrapper
rundeps    :
    - pyparsing
    - python-html5lib
    - python-isodate
    - python-nose
    - python-six
    - python-sparqlwrapper
build      : |
    %python3_setup
install    : |
    %python3_install
