name       : rdflib
version    : 4.2.1
release    : 2
source     :
    - https://github.com/RDFLib/rdflib/archive/4.2.1.tar.gz : c942f1dcd5a96d29ac6b8aad2f6ad1663c3fd2ed3586d567d0eb9208d05bd323
license    : BSD-3-Clause
component  : programming.python
summary    : RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
description: |
    RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
builddeps  :
    - pkgconfig(python-2.7)
    - pyparsing
    - python-html5lib
    - python-isodate
    - python-nose
    - python-setuptools
    - python-six
    - python-sparqlwrapper
rundeps    :
    - pyparsing
    - python-html5lib
    - python-isodate
    - python-nose
    - python-six
    - python-sparqlwrapper
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
