name       : rdflib
version    : 6.2.0
release    : 10
source     :
    - https://github.com/RDFLib/rdflib/archive/refs/tags/6.2.0.tar.gz : d4b920f44ad0f7bc4977d0163840bb2c4d9b8ec2d1dae92b0974d0d3d8b5a126
homepage   : https://github.com/RDFLib/rdflib
license    : BSD-3-Clause
component  : programming.python
summary    : A Python library for working with RDF, a simple yet powerful language for representing information
description: |
    RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
rundeps    :
    - pyparsing
    - python-html5lib
    - python-isodate
build      : |
    %python3_setup
install    : |
    %python3_install
